"""add number of likes column on Post model

Revision ID: fadf54e61c8a
Revises: 4a43a41f401f
Create Date: 2023-04-26 12:04:51.654110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fadf54e61c8a'
down_revision = '4a43a41f401f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_likes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('number_of_likes')

    # ### end Alembic commands ###
